stages:
  - build
  - deploy

# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login registry.gitlab.com -u hamidmoradik -p 423178511

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/halyab/halyab-web .
    - docker push registry.gitlab.com/halyab/halyab-web
  only:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: http://3tour.ir
  only:
  - master