# Official docker image.
image: docker:latest

# services:
#   - docker:dind

before_script:
  - docker login registry.gitlab.com -u hamidmoradik -p 423178511
  - docker build -t registry.gitlab.com/halyab/halyab-web .
  - docker push registry.gitlab.com/halyab/halyab-web


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# build:
#   stage: build
#   script:
#     - npm i
#     - npm run build

start:
  stage: build
  script:
    - npm -v